# Generated by Django 6.0.2 on 2026-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('requirements', models.TextField(blank=True)),
            ],
        ),
    ]
